### ISSUE TITLE
browser Add-Ons

### ISSUE THREAD

**Issue by Khodesaeed** [poyaz/cisco-socks-proxy#1]
Hi
Could you please introduce a browser Add-on and explain the configurations?

**Comment by poyaz** [comment]
Hi

I use Proxy [SwitchySharp](https://chrome.google.com/webstore/detail/proxy-switchysharp/dpplabbmogkhghncfbfdeeokoefdjegm) in chrome browser

If you use other browser, you can find Add-on like `Proxy SwitchySharp` in every browser.


---

### Configurations

In all proxy Add-on you should config Socks5 proxy with host and port proxy server

It's done :grin:

**Comment by Khodesaeed** [comment]
tnx.
